activity/act/urls.py
from django.conf.urls import patterns, include, url
from act.views_activity import *
from act.views_user import *

urlpatterns = patterns('',
    url(r'^register/$', register, name = 'register'),
    url(r'^login/$', user_login, name = 'login'),
    url(r'^logout/$', user_logout, name = 'logout'),
    url(r'^dashboard/$', dashboard, name = 'dashboard'),
    url(r'^user/(?P<user_name>[0-9a-zA-Z@_\.-]+)/request$', request_user_info, name = 'request_userinfo'),
    url(r'^user/(?P<user_name>[0-9a-zA-Z@_\.-]+)/page$', request_user_page, name = 'request_user_page'),
    url(r'^user/update$', update_user, name = "update_user"),
    url(r'^user/requestAll$', get_user_list, name = "get_user_list"),
    url(r'^activity/create$', create_activity, name = "create_activity"),
    url(r'^activity/(?P<SID>[0-9a-zA-z@_\.-]+)/request$', get_activity, name = "get_activity"),
    url(r'^activity/(?P<SID>[0-9a-zA-z@_\.-]+)/join$', participate_activity, name = "participate_activity"),
    url(r'^activity/(?P<SID>[0-9a-zA-z@_\.-]+)/quit$', quit_activity, name = "quit_activity"),
    url(r'^activity/(?P<SID>[0-9a-zA-z@_\.-]+)/vote$', vote, name = "vote_activity"),
    url(r'^activity/(?P<SID>[0-9a-zA-z@_\.-]+)/cancel_vote$', cancel_vote, name = "cancel_vote_activity"),
    url(r'^activity/requestAll$', get_activity_list, name = "get_activity_list"),
)

activity/activity/urls.py
from django.conf.urls import patterns, include, url
from django.conf import settings
from django.conf.urls.static import static

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'activity.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^$', 'activity.views.home', name='home'),
    url(r'^admin/', include(admin.site.urls)),
    # url(r'^comment/', include('django_comments.urls')),
    url(r'^act/', include('act.urls')),
) + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

activity/act/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.fields.files import ImageFieldFile, FileField
import uuid
import json
from django.utils import timezone
import datetime
from time import mktime

# Create your models here.


class MyJsonEncoder(json.JSONEncoder):

    def default(self, obj):
        if isinstance(obj, ImageFieldFile):
            return str(obj)
        elif isinstance(obj, datetime.date):
            # return int(mktime(obj.timetuple()))
            return obj.isoformat()
        else:
            return super(MyJsonEncoder, self).default(obj)


class UserProfile(models.Model):
    MALE = 1
    FEMALE = 2
    GENDER_CHOICES = (
        (MALE, 'male'),
        (FEMALE, 'female'),
    )
    user = models.OneToOneField(User, related_name = 'userprofile')
    avatar = models.ImageField(upload_to='profile_images', blank=True)
    Gender = models.IntegerField(choices = GENDER_CHOICES)
    Telephone = models.CharField(max_length=20)
    Type = models.IntegerField
    Messages = models.TextField
    Likes = models.TextField
    Comments = models.TextField

    def save(self):
        if not self.avatar:
            return super(UserProfile, self).save()
        super(UserProfile, self).save()
        from PIL import Image
        image = Image.open(self.avatar)
        size = (100, 100)
        image = image.resize(size, Image.ANTIALIAS)
        image.save(self.avatar.path)

    def __str__(self):
        return self.user.username


class Activity(models.Model):
    SID = models.CharField(
        max_length=100,
        blank=True,
        unique=True,
        default=uuid.uuid4)
    UID = models.ForeignKey(UserProfile, related_name='acts_admin')
    Title = models.CharField(max_length=128)
    Content = models.CharField(max_length=256, default='')
    IsPublic = models.BooleanField(default=True)
    Keyword = models.CharField(max_length=128)
    Members = models.ManyToManyField(User, related_name='acts_in')
    Image = models.ImageField(
        upload_to='activity_images',
        blank=True,
        default='')
    State = models.CharField(max_length=128)
    StartTime = models.DateField(default=timezone.now, null = True, blank = True)
    EndTime = models.DateField(default=timezone.now,null = True, blank = True)
    vote = models.IntegerField(default=0)
    RegisterForm = models.TextField
    BlackList = models.TextField

    @property
    def image(self):
        return self.Image

    @image.setter
    def image(self, value):
        self.Image = value


class CommentInfo(models.Model):
    ID = models.AutoField
    Title = models.CharField(max_length=128)
    Content = models.TextField
    UID = models.ForeignKey(UserProfile)
    SID = models.ForeignKey(Activity, default='')
    State = models.BooleanField(default=True)
    Score = models.IntegerField

    def __str__(self):
        return self.Title


class MessageInfo(models.Model):
    ID = models.AutoField
    UID = models.IntegerField
    TargetID = models.IntegerField
    Title = models.CharField(max_length=54)
    Content = models.TextField
    SendTime = models.DateField
    StateFrom = models.BooleanField(default=True)
    StateTo = models.BooleanField(default=True)

    def __str__(self):
        return self.Title

activity/act/forms.py
from django import forms
from act.models import UserProfile
from django.contrib.auth.models import User


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ('username', 'email', 'password')
    
    def __init__(self, *args, **kwargs):
        super(UserForm, self).__init__(*args, **kwargs)

        for fieldname in ['username', 'email', 'password']:
            self.fields[fieldname].help_text = None


class UserProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ('avatar', 'Gender', 'Telephone')
        widgets = {
            'avatar': forms.FileInput(attrs={'class': 'display:none'}),
            'Gender': forms.Select(attrs={'class': 'ui dropdown'}),
        }

activity/activity/views.py
from django.shortcuts import render, render_to_response
from django.template import RequestContext


# Create your views here.
def home(request):
    return render_to_response("index.html",context_instance=RequestContext(request))

activity/templates/act/act_detail.html
{% extends "base.html"%}
{% block content %}
{% load staticfiles %}
<style>
    #sid{
	visibility: hidden;
    }
    #user_status{
	visibility: hidden;
    }
    #vote_status{
	display: hidden;
    }
    .ui.card{
	min-width: 500px;
    }
</style>
<div class = "ui container">
<div class = "ui secondary menu">
    <a href="{% url 'dashboard' %}" class = "active item">
	Dashboard
    </a>
    <div class = "right menu">
	<a href = "{% url 'logout' %}" class = "ui item">
	    Logout
	</a>
    </div>
</div>
{% if isPublic %}
<div class = "ui centered card">
<div class = "content ui segments">
    <div class = "header ui segment">
	{{ title }}
	<div class = "ui right floated">
	    {% if voted %}
	    <i id = "vote" class = "red heart icon"></i>
	    {% else %}
	    <i id = "vote" class = "empty heart icon"></i>
	    {% endif %}
	    <span id = "votes" class = "description">{{ vote }}</span>
	</div>
    </div>
    <div class = "meta ui red segment">
	<div class = "ui grid container">
	    <div class = "four wide column">
		<i class = "user icon">{{ conductor }}</i>
	    </div>
	    <div class = "four wide column">
		<i class = "tags icon"> {{ Tags }}</i>
	    </div>
	    <div class = "four wide column">
		{{ State }}
	    </div>
	</div>
    </div>
    <div class = "description ui blue segment">
	{{ content }}
	<div class = "ui bottom floated">
	    <i class = "users icon"></i>
		{{member_count}} user(s) already in
	</div>
    </div>
    <div class = "extra ui green segment">

	<div class = "ui label">
	    {{ StartTime }}
	</div>
	To
	<div class = "ui label">
	    {{ EndTime }}
	</div>

	{% if myStatus %}
	<button id = "follow" class = "ui right floated toggle button active">Joined</button>
	{% else %}
	<button id = "follow" class = "ui right floated toggle button">Join</button>
	{% endif %}

    </div>
</div>
</div>
<div id = 'sid'>{{ sid }}</div>
<div id = "user_status">{{ myStatus }}</div>
<div id = "vote_status">{{ voted }}</div>
<h4 class = "ui horizontal divider header">
    <i class "user icon"></i>
    Members
</h4>
<div class = "ui centered card">
    <div class = "ui middle aligned animated list">
	{% for member in members %}
	<div class = "item">
	    <img class = "ui avatar image" src = "/media/{{member.avatar}}">
	    <div class = "content">
		<div class = "header">
		    <a href = "/act/user/{{member.user.username}}/page">
			{{ member.user.username }}
		    </a>
		</div>
	    </div>
	</div>
	{% endfor %}
    </div>
</div>
{% else %}
This is a private arrange
{% endif %}
</div>
<script src = "{% static "act/request_activity.js" %}"></script>
<script src = "{% static "jquery/jquery.cookie.min.js" %}"></script>
{% endblock %}

activity/templates/act/act_list.html
{% load staticfiles %}
<style>
    #list{
	margin: auto;
    }
</style>
<div id = "list" class = "ui centered cards">

</div>
<script id = "tmpl" type = "text/template" >
    <% _.each(data, function(item) {%>
	<div class = "card">
	    <div class = "content">
		<div class = "header">
		    <%= item.fields.Title %>
		</div>
		<div class = "ui grid">
		    <div class = "six wide column">
			By <%= item.fields.username %>
		    </div>
		    <div class = "six wide column">
			Tags : <%= item.fields.Keyword %>
		    </div>
		    <div class = "discription">
			<%= item.fields.Content %>
		    </div>
		    <div class = "six wide column">
			<%= item.fields.State %>
		    </div>
		    <div class = "six wide column">
			<%= item.fields.StartTime %> To <%= item.fields.EndTime %>
		    </div>
		</div>
		<a href="/act/activity/<%= item.fields.SID %>/request">
		    <div class = "ui bottom attached button">
			<i icon="add icon"></i>
			Join in
		    </div>
		</a>
	    </div>
	</div>
    <% }) %>
</script>
<script src = "{% static "act/request_activity_list.js" %}" ></script>

activity/templates/act/create_activity.html
<style>
    #activity{
	max-width: 500px;
	margin: auto;
    }
</style>
<form id = "activity" class = "ui form">
    {% csrf_token %}
    <div class = "field">
	<label> Title </label>
	<input name = "Title" type = "text" placeholder="Title"/>
    </div>
    <div class = "field">
	<label> Content </label>
	<input name = "Content" type = "text" placeholder="Content"/>
    </div>
    <div class = "field">
	<label> Keyword </label>
	<input name = "Keyword" type = "text" placeholder="Keyword"/>
    </div>
    <div class = "field">
	<label> State </label>
	<input name = "State" type = "text" placeholder="State"/>
    </div>
    <div class = "field">
	<label> Time Range </label>
	<div class = "two fields">
	    <div class = "field">
		<input class = "datepicker" name = "StartTime" type = "text" placeholder="StartTime:yyyy-mm-dd"/>
	    </div>
	    <div class = "field">
		<input class = "datepicker" name = "EndTime" type = "text" placeholder="EndTime:yyyy-mm-dd"/>
	    </div>
	</div>
    </div>
    <input class = "ui button" type = "submit" value = "submit" />
</form>
{% load staticfiles %}
<script src = "{% static "act/create_activity.js" %} " ></script>

activity/templates/act/dashboard.html
{% extends "base.html" %}
{% block content %}
{% load staticfiles %}

<div class = "ui container">
<div class = "ui top attached tabular menu">
    <a class = "item active" data-tab="activities"> Activities </a>
    <a class = "item" data-tab="personal"> Personal </a>
</div>
<div class = "ui bottom attached tab segment active" data-tab="activities">
    <h4 class = "ui horizontal divider header">
	<i class = "lightning icon"></i>
	Rock It !
    </h4>
    {% include "act/create_activity.html" %}
    <h4 class = "ui horizontal divider header">
	<i class = "send outline icon"></i>
	Activities
    </h4>
    {% include "act/act_list.html" %}
</div>
<div class = "ui bottom attached tab segment" data-tab="personal">
    <a class = "ui label">
	<img class = "ui right spaced avatar image" src = "/media/{{user.userprofile.avatar}}">
	    {{user.username}}
    </a>
    <div class = "ui centered card">
	<div class = "content">
	    <div class = "header">
		<a href ="{% url 'request_user_page' user.username %}">
		    My Activities
		</a>
	    </div>
	    <div class = "description">
		Click to Go
	    </div>
	</div>
    </div>
    <h4 class = "ui horizontal divider header">
	<i class = "write icon"></i>
	Update My Profile
    </h4>
    {% include "act/update_user.html" %}
    <div class = "ui clearing divider "></div>
    <span><i class = "power icon large"></i><a href="{% url 'logout' %}"  class = "ui tag red label">Log out</a></span>
</div>
<script src = "{% static "act/dashboard.js" %}"></script>
{% endblock %}

activity/templates/act/login.html
  {% extends "base.html" %}
  {% block content %}
  <style type="text/css">
    body {
      background-color: #1b1c1d;
    }
    body > .grid {
      height: 100%;
    }
    .image {
      margin-top: -100px;
    }
    .column {

	top: 50px;
      max-width: 450px;
    }

    .ui.container{
	margin:auto;
    }
	
	.ui.stacked.segment {
	  background-color: #1b1c1d;
	}
	
	
  </style>
  <script>
  $(document)
    .ready(function() {
      $('.ui.form')
        .form({
          fields: {
            email: {
              identifier  : 'username',
              rules: [
                {
                  type   : 'empty',
                  prompt : 'Please enter your username'
                }
              ]
            },
            password: {
              identifier  : 'password',
              rules: [
                {
                  type   : 'empty',
                  prompt : 'Please enter your password'
                },
                {
                  type   : 'length[6]',
                  prompt : 'Your password must be at least 6 characters'
                }
              ]
            }
          }
        })
      ;
    })
  ;
  </script>
</head>
<body>
<div class="ui container">

<div class="ui middle aligned center aligned grid">
  <div class="column">
    <h2 class="ui teal image header">
      <i class = "user icon"> </i>
      <div class="content">
        Log-in to your account
      </div>
    </h2>
    <form class="ui large form" method = "post" action = "/act/login/">
	{% csrf_token %}
      <div class="ui stacked segment">
        <div class="field">
          <div class="ui left icon input">
            <i class="user icon"></i>
            <input type="text" name="username" placeholder="username">
          </div>
        </div>
        <div class="field">
          <div class="ui left icon input">
            <i class="lock icon"></i>
            <input type="password" name="password" placeholder="Password">
          </div>
        </div>
        <div class="ui fluid large teal submit button">Login</div>
      </div>

      <div class="ui error message"></div>

    </form>

    <div class="ui message">
      New to us? <a href="/act/register/">Sign Up</a>
    </div>
  </div>
</div>
</div>
{% endblock %}

activity/templates/act/register.html
{% extends "base.html" %}
{% block content %}
  <style type="text/css">
    body {
      background-color: #A69F94;
      color : #D8E0F2;
    }
    body > .grid {
      height: 100%;
    }
    .image {
      margin-top: -100px;
    }
    .column {
      max-width: 450px;
    }

    .Upload{
	position: relative;
	overflow : hidden;
	margin:10px;
    }

    .Upload input#id_avatar{
	position: absolute;
	top: 0;
	right: 0;
	margin: 0;
	padding: 0;
	font-size : 20px;
	cursor: pointer;
	opacity: 0;
	filter: alpha(opacity=0);
    }
  </style>
{% if registered %}
Thanks for registration 
{% else %}


<div class="ui grid container">
    <div class = "four wide column">
    </div>
    <div class = "eight wide column">
	<p></p>
	<h4 class = "ui horizontal divider header">
	    <i class = "user icon"></i>
	    Register your account
	</h4>
	    <form id = "user_form" class = "ui large form" method = "post" action = "/act/register/" enctype = "multipart/form-data">
		    {% csrf_token %}
		    <div class = "field">
			<label>User Name</label>
			{{ user_form.username }}
		    </div>
		    <div class = "field">
			<label>E-mail</label>
			{{ user_form.email }}
		    </div>
		    <div class = "field">
			<label>Password</label>
			{{ user_form.password }}
		    </div>
			<!--<i class = "big photo icon"></i>-->
		    <div class = "Upload ui button ">
			<label>Avatar</label>
			{{ profile_form.avatar }}
		    </div>
		    <div class = "field">
			<label>Gender</label>
			{{ profile_form.Gender }}
		    </div>
		    <div class = "field">
			<label>Telephone</label>
			{{ profile_form.Telephone }}
		    </div>
		    <div>
			<input class = "ui fliud large submit button" type = "submit" name = "submit" value = "Register" >
		    </div>
	    </form>
    </div>
    <div class = "four wide column">
    </div>
</div>
{% endif %}
  <script>
  $(document)
    .ready(function() {
      $('select.dropdown').dropdown();
      $('.ui.form')
        .form({
          fields: {
            email: {
              identifier  : 'username',
              rules: [
                {
                  type   : 'empty',
                  prompt : 'Please enter your username'
                }
              ]
            },
            password: {
              identifier  : 'password',
              rules: [
                {
                  type   : 'empty',
                  prompt : 'Please enter your password'
                },
                {
                  type   : 'length[6]',
                  prompt : 'Your password must be at least 6 characters'
                }
              ]
            }
          }
        })
      ;
    })
  ;
  </script>
{% endblock %}

activity/templates/act/request_user.html
<input type = "text" id = "search" />
<input id = "btn" type = "button" value = "submit"/>
<div id = "result">
</div>
<script>
    $(document).ready(function(){
	$('#btn').click(function(event){
	    event.preventDefault();
	    var args = $('#search').val();
	    console.log(args);
	    var url = '/act/user/' + args;
	    $.get(url, function(data){
		console.log(data);
	    });
	})
    })
</script>

activity/templates/act/update_user.html
<form id = 'update' class = "ui form">
{% csrf_token %}
<div class = "field">
    <label> E-mail </label>
    <input type = "text" name = "email" placeholder = "E-mail"/>
</div>
<div class = "field">
    <label> original password </label>
    <input type = "text" name = "oldpassword" placeholder = "Original Passward"/>
</div>
<div class = "field">
    <label> new password </label>
    <input type = "text" name = "newpassword" placeholder = "New Passward"/>
</div>
<input class = "ui button" id = "submit" type = "submit" value = "Submit"></input>
</form>
<script>
    $(document).ready(function(){
	$('#update').submit(function(event){
	    event.preventDefault();
	    /*
	    var form_data = {
		user_name : $('input[name=user_name]').val(),
		email : $('input[name=email]').val(),
		oldpassword : $('input[name=oldpassword]').val(),
		newpassword : $('input[name=newpassword]').val()
	    }
	    */
	    var url = '/act/user/update';
	    /*
	    $.post(url, function(data){
		console.log(data);
	    });
	    */
	    $.ajax({
		url: url,
		type: 'post',
		dataType: 'json',
		data: $('form#update').serialize(),
		success: function(data){
		    console.log(data);
		}
	    });
	});
    });
</script>

activity/templates/act/user_info.html
{% extends "base.html" %}
{% block content %}
{% load staticfiles %}
<style>
    #username{
	display : none; 
    }
    #container{
	max-width: 500px;
	margin:auto;
    }
</style>
<div id = "container" class = "ui piles segment">
<div class = "ui secondary menu">
    <a href = "{% url 'dashboard' %}" class = "active item">
	Dashboard
    </a>
    <div class = "right menu">
	<a href = "{% url 'logout' %}" class = "ui item">
	    Logout
	</a>
    </div>
</div>
<div id = "username">{{ username}}</div>
<div id = "content"> </div>
</div>

<script type = "text/template" id = "tmpl">
	<div class = "ui centered card">
	    <div class = "image">
		<img src = "/media/<%= data.avatar %>">
	    </div>
	    <div class = "content">
		<div class = "header"><%= data.username %></div>
		<div class = "meta">
		    <% if ( data.Gender == 'male'){ %>
			<i class = "woman icon"></i>
		    <% } %>
		    <% if( data.Gender == 'female'){ %>
			<i class = "man icon"></i>
		    <% } %>
		</div>
		<div class = "description"> 
		    E-mail:
		    <%= data.Email %>
		</div>
	    </div>
	    <div class = "extra content">
		<a>
		    activities joined : <%= data.acts_count %>
		</a>
	    </div>
	</div>
	<h4 class = "ui horizontal divider header">
	    <i class = "certificate icon"></i>
	    Activities In
	</h4>
	<div class = "ui middle aligned animated list">
	    <% _.each(data.acts, function(item){ %>
		<div class = "item">
		    <div class = "content">
			<div class = "header">
			    <a href = "/act/activity/<%= item.sid %>/request">
				<%= item.title %>
			    </a>
			</div>
			<div class = "description">
			    <%= item.start_time %> to 
			    <%= item.end_time %>
			</div>
		    </div>
		</div>
	    <% }) %>
	</div>
	<h4 class = "ui horizontal divider header">
	    <i class = "checkmark icon"></i>
	    Activities Organized
	</h4>
	<div class = "ui middle aligned animated list">
	    <% _.each(data.acts_admin, function(item){ %>
		<div class = "item">
		    <div class = "content">
			<div class = "header">
			    <a href = "/act/activity/<%= item.sid %>/request">
				<%= item.title %>
			    </a>
			</div>
			<div class = "description">
			    <%= item.start_time %> to 
			    <%= item.end_time %>
			</div>
		    </div>
		</div>
	    <% }) %>
	</div>
</script>
<script src = "{% static "act/user_info.js" %}"></script>
{% endblock %}

activity/templates/base.html
<!DOCTYPE html>
<html>
    <head>
	<title> Neo </title>
        <meta charset="utf-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0">
	{% load staticfiles %}
	<link rel = "stylesheet" type = "text/css" href = "{% static 'semantic/dist/semantic.min.css' %} ">
	<script src = "{% static 'jquery/jquery-2.1.4.min.js' %} "></script>
	<script src = "{% static 'jquery/jquery-ui.min.js' %} "></script>
	<link rel = "stylesheet" type = "text/css" href = "{% static 'jquery/jquery-ui.min.css' %} "></script>
	<script src = "{% static 'underscore/underscore-min.js' %} "></script>
	<script src = "{% static 'semantic/dist/semantic.min.js' %} "></script>
	<script src="//use.edgefonts.net/josefin-sans.js"></script>
	<style>
	    *{
		font-family: josefin-sans, sans-serif;
	    }
	</style>
    </head>
    <body>


	{% block content %}
	{% endblock %}

    </body>
</html>

activity/templates/footer.html
<div class="ui inverted vertical footer segment">
    <div class="ui container">
      <div class="ui stackable inverted divided equal height stackable grid">
        <div class="three wide column">
          <h4 class="ui inverted header">About</h4>
          <div class="ui inverted link list">
            <a href="#" class="item">Sitemap</a>
            <a href="#" class="item">Contact Us</a>
            <a href="#" class="item">Religious Ceremonies</a>
            <a href="#" class="item">Gazebo Plans</a>
          </div>
        </div>
        <div class="three wide column">
          <h4 class="ui inverted header">Services</h4>
          <div class="ui inverted link list">
            <a href="#" class="item">Banana Pre-Order</a>
            <a href="#" class="item">DNA FAQ</a>
            <a href="#" class="item">How To Access</a>
            <a href="#" class="item">Favorite X-Men</a>
          </div>
        </div>
        <div class="seven wide column">
          <h4 class="ui inverted header">Footer Header</h4>
          <p>Extra space for a call to action inside the footer that could help re-engage users.</p>
        </div>
      </div>
    </div>
  </div>

activity/templates/header.html
<div class="ui large top fixed hidden menu">
    <div class="ui container">
        <a class="active item">Home</a>
        <a class="item">Work</a>
        <a class="item">Company</a>
        <a class="item">Careers</a>
        <div class="right menu">
            <div class="item">
                <a class="ui button">Log in</a>
            </div>
            <div class="item">
                <a class="ui primary button">Sign Up</a>
            </div>
        </div>
    </div>
</div>
<!-- Sidebar Menu -->
<div class="ui vertical inverted sidebar menu">
    <a class="active item">Home</a>
    <a class="item">Work</a>
    <a class="item">Company</a>
    <a class="item">Careers</a>
    <a class="item">Login</a>
    <a class="item">Signup</a>
</div>

activity/templates/index.html
{% extends "base.html" %}
{% block content %}
<style type="text/css">

    .hidden.menu {
      display: none;
    }

    .masthead.segment {
      min-height: 700px;
      padding: 1em 0em;
    }
    .masthead .logo.item img {
      margin-right: 1em;
    }
    .masthead .ui.menu .ui.button {
      margin-left: 0.5em;
    }
    .masthead h1.ui.header {
      margin-top: 3em;
      margin-bottom: 0em;
      font-size: 4em;
      font-weight: normal;
    }
    .masthead h2 {
      font-size: 1.7em;
      font-weight: normal;
    }

    .ui.vertical.stripe {
      padding: 8em 0em;
    }
    .ui.vertical.stripe h3 {
      font-size: 2em;
    }
    .ui.vertical.stripe .button + h3,
    .ui.vertical.stripe p + h3 {
      margin-top: 3em;
    }
    .ui.vertical.stripe .floated.image {
      clear: both;
    }
    .ui.vertical.stripe p {
      font-size: 1.33em;
    }
    .ui.vertical.stripe .horizontal.divider {
      margin: 3em 0em;
    }

    .quote.stripe.segment {
      padding: 0em;
    }
    .quote.stripe.segment .grid .column {
      padding-top: 5em;
      padding-bottom: 5em;
    }

    .footer.segment {
      padding: 5em 0em;
    }

    .secondary.pointing.menu .toc.item {
      display: none;
    }

    @media only screen and (max-width: 700px) {
      .ui.fixed.menu {
        display: none !important;
      }
      .secondary.pointing.menu .item,
      .secondary.pointing.menu .menu {
        display: none;
      }
      .secondary.pointing.menu .toc.item {
        display: block;
      }
      .masthead.segment {
        min-height: 350px;
      }
      .masthead h1.ui.header {
        font-size: 2em;
        margin-top: 1.5em;
      }
      .masthead h2 {
        margin-top: 0.5em;
        font-size: 1.5em;
      }
    }


  </style>
 <script>
  $(document)
    .ready(function() {

      // fix menu when passed
      $('.masthead')
        .visibility({
          once: false,
          onBottomPassed: function() {
            $('.fixed.menu').transition('fade in');
          },
          onBottomPassedReverse: function() {
            $('.fixed.menu').transition('fade out');
          }
        })
      ;

      // create sidebar and attach to menu open
      $('.ui.sidebar')
        .sidebar('attach events', '.toc.item')
      ;

    })
  ;
  </script>


<!-- Page Contents -->
<div class="pusher">
  <div class="ui inverted vertical masthead center aligned segment">

    <div class="ui container">
      <div class="ui large secondary inverted pointing menu">
        <a class="toc item">
          <i class="sidebar icon"></i>
        </a>
        <a class="active item" href="/">Home</a>
	<a href = "{% url 'dashboard' %}" class="item">Dashboard</a>
        <div class="right item">
          <a class="item" href="/act/login/">Login</a>
          <a class="item" href="/act/register/">Signup</a>
        </div>
      </div>
    </div>

    <div class="ui text container">
      <h1 class="ui inverted header">
	  OUT OR NOT
      </h1>
      <h2>FOR YOUR ACTIVITIES</h2>
      <a href = "{% url 'dashboard' %}">
	  <div class="ui huge primary button">Get Started <i class="right arrow icon"></i></div>
      </a>
    </div>

  </div>


{% endblock %}

activity/templates/menu.html
<div class = "ui secondary menu">
    <a href = "{% url 'dashboard' %}" class = "active item">
	Dashboard
    </a>
    <div class = "right menu">
	<a href = "{% url 'logout' %}" class = "ui item">
	    Logout
	</a>
    </div>
</div>